version: '3.8'

services:
  game-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped